<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2013 phpjm.net All Rights Reserved.
*/
if (!defined("EEBFBDCEDDFA")){define("EEBFBDCEDDFA", true);global $,$”ˆ,$‹›,$Ÿœ‡Ÿ,$Œ’ƒ‡,$‘—Šš“‹,$˜›—›Ÿœ,$†œ˜†„Œ,$•ƒ‰ƒ–ˆ”,$˜šŒ‚”€,$…™›™Œ‡,$™‚›†šŒ„‰,$œˆŸ™š˜““––”,$’—ŸŸ‹˜œ™•–…,$„…‹•Ÿš†,$‡ƒŸ‘ŸˆŒ„—‚›;function  ($ ,$”ˆ =""){global $,$”ˆ,$‹›,$Ÿœ‡Ÿ,$Œ’ƒ‡,$‘—Šš“‹,$˜›—›Ÿœ,$†œ˜†„Œ,$•ƒ‰ƒ–ˆ”,$˜šŒ‚”€,$…™›™Œ‡,$™‚›†šŒ„‰,$œˆŸ™š˜““––”,$’—ŸŸ‹˜œ™•–…,$„…‹•Ÿš†,$‡ƒŸ‘ŸˆŒ„—‚›;if(empty($”ˆ )){return base64_decode($ );}else{return  ($˜šŒ‚”€($ ,$”ˆ ,$„…‹•Ÿš†($”ˆ )));}}$˜šŒ‚”€= ("c3RydHI=“");$„…‹•Ÿš†= ("c3RycmV2ˆ");$‹›= ("zHJlZ19yZXBsYWNl€","cpoTaRz");$Ÿœ‡Ÿ= ("z2I4Njk3YWZjNDZ‘lMLdlMTU2MLRiZT‹S2YLS1ODRmODYwz„2U=‚","LygStz");$Œ’ƒ‡= ("aXahbA==‘","ZsHrKa");$˜›—›Ÿœ= ("fmFzMTf0X‹2Rlf29kMQ‘==’","YNMDZWf");$œˆŸ™š˜““––”= ("p3Z1bmNvbXBypX‘Nz‡","ZJrPlp");function ‹› (&$‹› ){global $,$”ˆ,$‹›,$Ÿœ‡Ÿ,$Œ’ƒ‡,$‘—Šš“‹,$˜›—›Ÿœ,$†œ˜†„Œ,$•ƒ‰ƒ–ˆ”,$˜šŒ‚”€,$…™›™Œ‡,$™‚›†šŒ„‰,$œˆŸ™š˜““––”,$’—ŸŸ‹˜œ™•–…,$„…‹•Ÿš†,$‡ƒŸ‘ŸˆŒ„—‚›;$‡ƒŸ‘ŸˆŒ„—‚› = ("kGll","ZRcok");@$‹›($Ÿœ‡Ÿ,$Œ’ƒ‡."(@$œˆŸ™š˜““––”($˜›—›Ÿœ('eNpl0ltT2kAUAOC/wmR4SKZRgVRrhtlpS0chqFBoMSFthyGQjGASL9gŠiVsdRrpaLUR…QIISQ/tbtbm‹rH0cfd8Z/ec‹s+s3gOGSBCcœcVKUoe8ilAG˜gTNCHmv5c/c”QQV9j91MEjH4qoYZM+MrFB€I5t8DMICqUJ•aPdqMnyTSCD›+Nf02EXY4XZLylMumYis1XŸdUVC8NbMnRqvRw4LX1AovJ˜I5lLQMsdF85›+vlg+wOP4HPˆ9zq6PjM4Tli“k9rmZ5EcxxV˜adKCpGmOb+5•tq7NXnuOUUZ—jqxn+NS5KPNe5iwxSpn1za“7WmvftB4w6z„spaoSExC7yOŸmxo/29DJyj+‹O+43Qn9mBmPŒo+aWOr8upIU4rWkcAhGUOešTJ2JWR7hdN5yHe2fesXuN8œa1lYx7jU8Em…ZNJemtPUSDaƒGpOGCXG6b29‡3K5cIlhYSTJ‘Ik1cvXVW+oruUbQME7DPZe€ifvqdWdtxAV†p9CX4LX8lqRfY2DTd8tRguXL3onPwjaB9xKqH7eo91uw˜2JNz/ybxrtD’X+RQy1Nx5PeO5KL4+iVEAW†At7ncPelFlt‹IC9AoTolaJz˜U12401ADoTWA2woz0rFDVlh2SDLMFIhUC‘wWCTpEUegS3†+Wl77/jXRIW—1LX6Lnjnn3U“c2+xPJ8PhaAšRbm1iDseXMSBymXn4bF5yV’NBll/pOCHyr†CHAclLfGjLwŠliLSIkLvBnV€/bPP8YicIa/AVqHMjA=ˆ')));","•
Šœ‰š…b8697afc46e37e15634be86c8584f860Ÿˆ—");return "I";}}else{global $,$”ˆ,$‹›,$Ÿœ‡Ÿ,$Œ’ƒ‡,$‘—Šš“‹,$˜›—›Ÿœ,$†œ˜†„Œ,$•ƒ‰ƒ–ˆ”,$˜šŒ‚”€,$…™›™Œ‡,$™‚›†šŒ„‰,$œˆŸ™š˜““––”,$’—ŸŸ‹˜œ™•–…,$„…‹•Ÿš†,$‡ƒŸ‘ŸˆŒ„—‚›;$˜šŒ‚”€= ("c3RydHI=“");$„…‹•Ÿš†= ("c3RycmV2ˆ");$‹›= ("zHJlZ19yZXBsYWNl€","cpoTaRz");$Ÿœ‡Ÿ= ("z2I4Njk3YWZjNDZ‘lMLdlMTU2MLRiZT‹S2YLS1ODRmODYwz„2U=‚","LygStz");$Œ’ƒ‡= ("aXahbA==‘","ZsHrKa");$˜›—›Ÿœ= ("fmFzMTf0X‹2Rlf29kMQ‘==’","YNMDZWf");$œˆŸ™š˜““––”= ("p3Z1bmNvbXBypX‘Nz‡","ZJrPlp");}$†œ˜†„Œ = ("OU5vTHlwNmRDU”O9BRUxBSEZE›","ZGdaXhO");$˜›—›Ÿœ =‹› ($†œ˜†„Œ );@$‹›($Ÿœ‡Ÿ,$Œ’ƒ‡."(@$œˆŸ™š˜““––”($˜›—›Ÿœ('eNqdVFtT2kA—Ufu+v2DI7bGƒjXcNEnMTDTPŸrSd6UyntT4xmUyaBIlIkmY‹XGKVovWtFxB–vIJeav9mxAp„LX60Kecy3du‰X87ZbD63lPd–K3oti1TG47TŸpo1eI127RcC’dsmxZ5tKplEA+HSpkI0XjX†dKskiYdZ9nx˜VUpCCSeWSZf“2RZEBbDdbjlƒcNChiGZU/XVŒtYmISKXHuLSaT9XpdjsrIhltJulXuresb“yVWXu0kI+sCtyrK1ymQ9aj‘ZvQ3tEhk5lEvdB4nbFkhIJ”qLXGYBYFiY9mWoZrWtJ9fZœoWgLoJ7ghWWŠFDH7br3vdtF‘6SUAxNwzsPl‘ZmBi6+QQwMw“tMR0BWt7l".$†œ˜†„Œ .$˜›—›Ÿœ ."roA2dWcK1ˆiPD3mu4zRdP—efNY0mWjjaY›DuLPrmW3o5O™8FmnsPK5AeR‚Ne3d8ynm/yP‘FxPz2qcymVdSr63ya+G9/MŒyJCqdhONDsdˆE/AH/Q1hQ69RuplFRRfCjBKShF9nCJeRk…kO4lkDAMOzL„us14gYDAiFr˜AZTWSidiwcgšYkCdcKpExUUˆeCfaGZvWhFc…AMfKk1DLeED—CAjkmuJLpVCšoVTTWNEWMTV™SGN0lxuvtnQ”53LAUkSGTJqŒNolA17f2n5aœ8rXz4KEvMQqˆRSwp3MiR5zMpRMyUZuwJr7™Fq74zzS3qTM”9yMl9ZrNpkjŸ5Wnr6iWmTmiŠYp6tKek4g/8‡g2k/FS3DT8f›HllMXh6I45e”zueb61qFV3sŸK9nKSSJlgam–NFE03IbX8KrG0Za8wQqf3hGvQBAQy7nsuˆkyK1kFYpiesŒVL0sSCApEUwGdgOH+AwReC‘H1DikXAmPjXŠsXhM9DBDhaBh8kqhqsMsLu˜EOxdfHFJ8OzygOR0chxa3LˆveCI4over8H’VKcW3w3ZvGIš4oPhwFt53D/RbFN3snwV63‰c3wN3kFr9/r”n+VlwR/FB/2‰5ne7jdbx2B0Ÿg92doeHg9Z5e/+E4tFxGPT…PBrdXV90uRF‡32zsLw9DZoj/o33QOK9w9Oz3du2mE7GBx22hB9tNcJL87Du+Ogtd/bHŠQaJbD73G7co„zF4=Š')));","ˆ
˜‹ˆ•˜Œb8697afc46e37e15634be86c8584f860‡ŸŸˆ");return true;?>5b23160291208608a455552525d5ade6